[project]
name = "c-harness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matheus B A", email = "matheus.buniotto@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "rich>=15.0.0",
]

[project.scripts]
c-harness = "c_harness:main"

[build-system]
requires = ["uv_build>=0.11.1,<0.12.0"]
build-backend = "uv_build"
